### ISSUE TITLE
Use str values 'nested' and 'ring' for order everywhere

### ISSUE THREAD

**Issue by cdeil** [cdeil/healpix#40]
I see that in the Cython API we currently use int for `order`:
```
order : int
Order of HEALPix pixels. Set this to 0 for nested order or 1 for ring order.
```
http://healpix.readthedocs.io/en/latest/api/healpix.core_cython.healpix_to_lonlat.html
whereas in the other parts of our API we use str for `order`:
```
order : { ‘nested’ | ‘ring’ }, optional
Order of HEALPix pixels
```
http://healpix.readthedocs.io/en/latest/api/healpix.core.healpix_to_lonlat.html

I think the str form is easier to use / remember and there are no efficiency concerns with the handling of this argument (true?), and consistency is good, so I'd suggest to change the Cython functions to use str for order as well.

@astrofrog - Thoughts?

If you agree it's a good change, I could make a PR for this.

**Comment by astrofrog** [comment]
The reason for using integers in Cython was for performance, though I guess that the actual functions could take a string and convert internally. We definitely don't want to be comparing strings inside the loops.

Feel free to make a PR!

**Comment by cdeil** [comment]
I think there should never be an if/else for order inside a pixel loop. Even an if / else with int is slow.

Instead this if / else should be outside the pixel loop. I'm not how to do it best, it might be necessary to introduce a few more functions that do ring / nested separately in the Cython layer.

I don't have time to start a PR in the near future. Possibly this is something that could be done in one go with #21 if someone has time to code on the Cython wrapper.

**Comment by astrofrog** [comment]
I just checked the code and it's just the interpolation and cone search for which there is an 'if' inside the loop. I originally had separate functions for ring and nested for all functions but since cython functions have quite a lot of code overhead per function, I found it tidier to have just one e.g. ``healpix_to_lonlat`` function rather than have ``healpix_to_lonlat_ring`` and ``healpix_to_lonlat_nested``. So one option is to just adjust the interpolation and cone search ones to put the if outside the loop but keep one function.

Another option is indeed to split all functions, but if this is done I would recommend putting the nested and ring functions in two separate files so they can easily be diff-ed to check that they are in sync otherwise. (Or we could even consider writing one file as a template and auto-generating the Cython for nested and ring functions, but that seems a bit too much).

**Comment by cdeil** [comment]
I think there might be other options to change (hopefully for the better) the Cython interface.

One could be to have xy / ring / nested converters that work on arrays, like you already have `ring_to_nested`.

Another could be to move some of the functions from Cython to Python, and have them call into short few-line Cython functions that in most cases just do the array element loop, calling into the right C function for each element. In that case I think more functions would be fine (because each is just a few lines, and especially the ~ 30-line docstring isn't duplicated. Plus this would resolve #21 without any extra work of supporting n-dim arrays in the Cython code, no? (I'm not very familiar with Cython, but it should be possible without any extra work to process n-dim arrays as if they are 1-dim flat arrays, no?)

**Comment by astrofrog** [comment]
> One could be to have xy / ring / nested converters that work on arrays, like you already have ring_to_nested.

We should avoid this, because it would mean creating temporary arrays, which would perform a lot worse than the current code for large arrays (e.g. if you needed an array to hold the xy values)

> Another could be to move some of the functions from Cython to Python, and have them call into short few-line Cython functions that in most cases just do the array element loop, calling into the right C function for each element. In that case I think more functions would be fine (because each is just a few lines, and especially the ~ 30-line docstring isn't duplicated. 

I don't understand what you mean here - I thought this is what currently happens? The Cython is in most cases just the looping over array elements. As mentioned above, we do have to make the final array in that loop because we want to avoid as much as possible making temporary arrays. If you look at https://github.com/cdeil/healpix/blob/master/healpix/core_cython.pyx#L59, it really is just 3 lines of Cython. This should not be split into two functions that have two lines of Cython (one for healpixl_nested_to_xy and the other for healpixl_to_radec) because then we'd have to make a temporary array.

I'm still open to the idea of splitting the ring and nested parts into two separate functions each time, and we could decide to get rid of the docstrings or simplify them by linking to the Python equivalents with intersphinx.

> Plus this would resolve #21 without any extra work of supporting n-dim arrays in the Cython code, 
no? (I'm not very familiar with Cython, but it should be possible without any extra work to process n-dim arrays as if they are 1-dim flat arrays, no?)

I'm pretty sure this is not possible and should instead be done at the Python level. It's easy to do in Python since you can just do something like:

```
shape_orig = array.shape
array = array.ravel()
...
array = array.reshape(shape_orig)
```

without any copying (``ravel`` returns a C-contiguous array)

I guess I don't see the point in completely changing how the cython code is organized at this point - for many of the functions it's fine to switch ``order`` to be a string. For ``interpolate_bilinear_lonlat`` there are already lots of if statements in the loop, so it's fine to just convert order to an int and do the check in the loop without loss of performance. And ``healpix_cone_search`` can be adjusted to be more like the other functions, with the if statement outside the loop.

I think we should first make these changes and the discuss separately whether we can move more of the Cython code to Python or reduce the size of the docstrings.

**Comment by cdeil** [comment]
@astrofrog - As you're probably noticed, I have very little knowledge / experience about Cython, and unfortunately also don't have time to learn / try out things and really help with the Cython interface in the healpix package.

Just one more thought: from what I gather, memoryviews are the more modern way to write the Numpy array interface code and you're still using the "old" way to write Cython functions that process Numpy arrays?
http://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html
Like I said, I'm a complete beginner to this, and it's not clear to me if there would be real advantages (like simpler code or not having to ravel / reshape manually before calling into the Cython function) for the Cython code here.

**Comment by astrofrog** [comment]
@cdeil - ah good point about memory views, I'll take a look!

**Comment by astrofrog** [comment]
@cdeil - just to check, shall i go ahead and make the changes you suggested here about order being a string? Or were you planning on doing a PR?

**Comment by cdeil** [comment]
@astrofrog - If you can do it here, that would be great!

**Comment by astrofrog** [comment]
Done in #42 :)
