### ISSUE TITLE
[doctest] docs/cone_search.rst fail

### ISSUE THREAD

**Issue by cdeil** [cdeil/healpix#41]
There's a fail for `[doctest] docs/cone_search.rst` on travis-ci:
https://travis-ci.org/cdeil/healpix/jobs/279819620#L965

I don't see that locally (because doctests don't work for me, see #32), but I'll try to resolve this now, i.e. have a look at that test case, compare what healpy gives, and see if the old or new result are correct.

**Comment by cdeil** [comment]
@astrofrog - I get different results from `healpy.query_disc`.

test script:
```python
import astropy.units as u
import healpy
from healpix import CelestialHEALPix
from astropy.coordinates import Galactic, SkyCoord

coord = SkyCoord('00h42m44.3503s +41d16m08.634s')
radius = 5 * u.arcmin

hp = CelestialHEALPix(nside=16, order='nested', frame=Galactic())
idx = hp.cone_search_skycoord(coord, radius=radius, approximate=False)
print('healpix:', idx)

coord = coord.galactic
vec = healpy.ang2vec(coord.l.deg, coord.b.deg, lonlat=True)
radius = radius.to('radian').value
idx = healpy.query_disc(nside=16, vec=vec, radius=radius, nest=True, inclusive=False)
print('healpy non-inclusive:', idx)
idx = healpy.query_disc(nside=16, vec=vec, radius=radius, nest=True, inclusive=True)
print('healpy inclusive:', idx)
```
output:
```
healpix: [2537]
healpy non-inclusive: []
healpy inclusive: [2531 2536 2537]
```

I had a very quick look at the implementation and didn't find an obvious bug, arguments seem to be passed down to `healpix_cone_search` correctly. I guess there could be a bug in `healpix_rangesearch_radec_simple`?  There are no tests against healpy yet for this functionality. 

@dstndstn - Thoughts?

---

@astrofrog - A question concerning the `healpix_cone_search` implementation and other Cython functions that have the if-else for `order` in the pixel loop:
```python
    for i in range(n_indices):
        index = indices[i]
        if order == ORDER_NESTED:
            result[i] = healpixl_xy_to_nested(index, nside)
        else:
            result[i] = healpixl_xy_to_ring(index, nside)
```
Would moving the if/else before the pixel loop work / be faster?
```python
transform = healpixl_xy_to_nested if ORDER_NESTED else healpixl_xy_to_ring
for i in range(n_indices):
     result[i] = transform(indices[i], nside)
```

**Comment by astrofrog** [comment]
@cdeil - regarding performance, this might make it slower because python variables that are python objects (in this case functions) may not actually get optimized by Cython (hence the current code, where an int comparison is fast). I keep meaning to set up asv so could test this though.

**Comment by astrofrog** [comment]
Regarding the original issue here, it might be worth trying to make a plot of the boundaries of the pixels that are returned to try and understand why the results might be different.

**Comment by astrofrog** [comment]
@cdeil - I looked into this, and I'm actually wondering if healpy might be wrong. Check this out:

![debug](https://user-images.githubusercontent.com/314716/31031831-c5de4edc-a551-11e7-9322-9402878350a8.png)

Red is our library, blue is healpy inclusive and green is healpy non-inclusive

* In the top left sub-plot, healpy is returning pixels that don't overlap at all with the circle
* In the top right sub-plot, again one of the pixels doesn't overlap
* In the botton left sub-plot, things seem ok
* In the bottom right subplot, the non-inclusive one (if I understand what that is) is including some pixels that probably it shouldn't be

In all cases our results (red) seem sensible assuming we're looking for any overlap.

In future we could add an option to ours to have only pixels fully inside - this is easy to check since we just need to make sure the four corners are inside the circle.

By the way, I deliberately picked an area at zero latitude to avoid distortion effects for the circle. In any case the top left one shows a circle small enough this shouldn't matter.

**Comment by astrofrog** [comment]
Ah ok I misunderstood the inclusive option:

*If False, return the exact set of pixels whose pixel centers lie within the disk; if True, return all pixels that overlap with the disk, and maybe a few more. Default: False*

Given this, I think it's ok - they do say they might return some that don't overlap.

Our function returns any pixel that overlaps with the search cone, which I think is acceptable behavior. It just means we can't write a healpy compatibility function (their behavior is going to be hard to emulate, at least for the inclusive option. The non-inclusive option is easy to emulate.

I vote for not doing anything at this point apart from clarifying in our docstring that this returns any pixel that overlaps.

**Comment by astrofrog** [comment]
The original issue here has been resolved. As for the cone search, I have clarified the docstring, but I don't think there's anything else we need to do. So @cdeil, feel free to close it once you've taken a look at my findings.

**Comment by cdeil** [comment]
@astrofrog - Awesome, thank you!!!
